### ISSUE TITLE
Öffnen in Visual Studio

### ISSUE THREAD

**Issue by pixelspezi** [BillerFaktura/Biller.App#18]
Hi, wie sind die Vorraussetzungen wenn man mit entwickeln möchte? Ich habe es versucht in Visual Studio zu öffnen was leider nicht geklappt hat.

**Comment by ilueckel** [comment]
Ich habe eine kurze Anleitung geschrieben. Damit klappt es hoffentlich: https://github.com/BillerFaktura/Biller.App/wiki/Build-Biller-in-Visual-Studio

Ob das ganze auch in der Express Edition so funktioniert kann ich aber leider nicht sagen

**Comment by pixelspezi** [comment]
Ok. Jetzt hat es geklappt. Habe es jeweils mit der Express und mit der Pro probiert.
Ich erhalte immer dieses Fenster

![screen](https://cloud.githubusercontent.com/assets/7807675/4668488/be2711c2-5565-11e4-856b-9a4d48407816.PNG)

**Comment by ilueckel** [comment]
Laden Sie sich noch das Biller.XDatabase Paket herunter und erstellen sie es. Kopieren Sie dann die XDatabase@Biller.dll vom Debugordner des Pluginverzeichnises in den Debugordner vom Biller.App Projekt

**Comment by pixelspezi** [comment]
Ok. Das hat funktioniert. Danke :)
